steps:
# test
# - name: 'fdfdfdf'
#   id: Unit Test
#   args: []
  
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '.'
  
# This step pushes the image to Container Registry

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'

# Deploy image to Cloud Run Google Cloud 
- name: 'gcr.io/cloud-builders/gcloud'
  id : Deploy to Cloud Run
  args:
  - 'run'
  - 'deploy'
  - 'express-cicd'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME-$SHORT_SHA'
  - '--region'
  - asia-southeast1 
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'